var canvas=document.querySelector("canvas");function scaleCanvas(){canvas.width=window.innerWidth;canvas.height=window.innerHeight}scaleCanvas();var ctx=canvas.getContext("2d");ctx.font="28px Verdana";ctx.fillStyle="#ffa801";var holdtime,starttime,best=0;function Point(a,c){this.x=a;this.y=c;this.prevX=this.targetX=this.x;this.update=function(){this.x<this.targetX?this.x+=(this.targetX-this.x)/4:this.x>this.targetX&&(this.x-=(this.x-this.targetX)/4)}}
function Obstacle(a,c,b){this.x=a;this.y=c;this.radius=b;this.draw=function(){ctx.fillStyle="#ffffff";ctx.beginPath();ctx.arc(this.x,this.y,this.radius,0,2*Math.PI);ctx.fill();ctx.closePath();getDistance(player.x,player.y+80,this.x,this.y)<player.radius+this.radius&&(fail=!0)};this.update=function(){this.y+=8+this.radius/10;this.draw()}}
function Player(a,c,b){this.x=a;this.y=c;this.radius=b;this.nearestPoint=void 0;this.wave=0;this.arms=this.flipped=!1;this.moveDelta=0;this.failTimer=new Date;this.draw=function(){ctx.lineCap="round";ctx.lineJoin="round";fail&&(this.y+=this.radius);1<this.wave?this.flipped=!0:-1>this.wave&&(this.flipped=!1);this.wave=this.flipped?this.wave-.5:this.wave+.5;void 0!=this.nearestPoint&&(ctx.strokeStyle="#FF6C09",50>Math.abs(this.nearestPoint.x-this.x)&&!fail?(ctx.beginPath(),ctx.moveTo(this.nearestPoint.x,
this.nearestPoint.y),ctx.lineTo(this.x-.7*this.radius,this.y+50),ctx.moveTo(this.x+.5*this.radius,this.y+50),ctx.lineTo(this.nearestPoint.x,this.nearestPoint.y),ctx.stroke(),this.arms=!1,this.failTimer=0,holdtime=Math.floor((new Date-starttime)/10)/100,ctx.fillStyle="#FF6C09",ctx.font="48pt Helvetica",ctx.fillText(holdtime+"s",20,70)):(ctx.beginPath(),ctx.moveTo(this.x-this.radius/2,this.y+50),ctx.lineTo(this.x-(this.radius+30),this.y+50+15*Math.sin(this.wave)),ctx.moveTo(this.x+this.radius/2,this.y+
50),ctx.lineTo(this.x+(this.radius+30),this.y+50+15*Math.sin(this.wave)),ctx.stroke(),this.arms=!0,0==this.failTimer&&(this.failTimer=new Date)),ctx.beginPath(),this.nearestPoint.x<this.x-20&&!this.arms?ctx.arc(this.x-7,this.y-this.radius+50,.7*this.radius,0,2*Math.PI):this.nearestPoint.x>this.x+20&&!this.arms?ctx.arc(this.x+7,this.y-this.radius+50,.7*this.radius,0,2*Math.PI):ctx.arc(this.x,this.y-this.radius+50,.7*this.radius,0,2*Math.PI),ctx.fillStyle="#FF6C09",ctx.fill(),ctx.closePath(),ctx.beginPath(),
ctx.moveTo(this.x+this.moveDelta-10,this.y+85),ctx.lineTo(this.x-10,this.y+55),ctx.lineTo(this.x+10,this.y+55),ctx.lineTo(this.x+this.moveDelta+10,this.y+85),ctx.stroke(),ctx.closePath(),0>this.moveDelta?this.moveDelta+=Math.abs(this.moveDelta)/4:0<this.moveDelta&&(this.moveDelta-=this.moveDelta/4),ctx.beginPath(),ctx.arc(this.x,this.y+55,this.radius,0,2*Math.PI),ctx.fillStyle="#FF6C09",ctx.strokeStyle="#FF6C09",ctx.fill(),ctx.stroke(),ctx.closePath());0<this.failTimer&&!fail&&1E3<new Date-this.failTimer&&
(fail=!0)}}for(var pointCount=30,dist=innerHeight/(pointCount-1),pointArray=[],interval=0,limit=60,steps=0,difficulty=innerWidth/6,i=0;i<pointCount;i++)pointArray.push(new Point(innerWidth/2,i*dist));var fail=!1,start=!1,player=new Player(innerWidth/2,innerHeight/2,15),obstacles=[],increase=!1;player.nearestPoint=pointArray[Math.ceil(pointArray.length/2)-3];
function animate(){window.requestAnimationFrame(animate);ctx.clearRect(0,0,innerWidth,innerHeight);interval++;ctx.lineWidth=6;ctx.beginPath();for(var a=0;a<pointArray.length;a++)0==a?(ctx.strokeStyle="#2c3e50",ctx.moveTo(pointArray[a].x,pointArray[a].y),fail?(ctx.font="48pt Helvetica",ctx.fillText(holdtime+"s",20,70),ctx.font="14pt Helvetica",ctx.fillText("Click para empezar",20,95)):interval>=limit&&(pointArray[a].targetX=(Math.random()-.5)*difficulty+innerWidth/2,difficulty+=10,difficulty>innerWidth/
2&&(difficulty=innerWidth/2),interval=0,steps++,30<=steps&&(limit-=5,10>limit&&(limit=10),steps=0))):(ctx.lineTo(pointArray[a].x,pointArray[a].y),fail||(pointArray[a].targetX=pointArray[a-1].x)),pointArray[a].update();ctx.stroke();player.draw();start=!0;if(8<holdtime)for(0!=Math.floor(holdtime)%10||increase||(obstacles.push(new Obstacle(player.x+(Math.random()-.5),-50,30*Math.random()+10)),increase=!0),0!=Math.floor(holdtime)%10&&(increase=!1),a=0;a<obstacles.length;a++)obstacles[a].update(),obstacles[a].y>
innerHeight+obstacles[a].radius+10&&!fail&&(obstacles[a]=new Obstacle(player.x+(Math.random()-.5),-50,30*Math.random()+10));ctx.font="12pt Helvetica";ctx.fillStyle="#2c3e50";0<best?(a=best,holdtime>best&&(a=holdtime),ctx.fillText("RECORD:"+a,20,20)):ctx.fillText("R.U.N.E",20,20)}var prevMouseX=innerWidth/2;
window.addEventListener("mousemove",function(a){if(!fail){player.x=a.pageX;player.y=a.pageY;a=void 0;for(var c=1E4,b=0;b<pointArray.length;b++)Math.abs(pointArray[b].y-player.y)<c&&(c=Math.abs(pointArray[b].y-player.y),a=pointArray[b]);void 0!=a&&(player.nearestPoint=a);player.moveDelta-=player.x-prevMouseX;prevMouseX=player.x}});
window.addEventListener("mousedown",function(a){fail&&(holdtime>best&&updateScore(holdtime),player=new Player(a.pageX,a.pageY,15),this.failTimer=0,fail=!1,starttime=new Date,obstacles=[])});function getDistance(a,c,b,d){return Math.sqrt(Math.pow(Math.abs(a-b),2)+Math.pow(Math.abs(c-d),2))}function updateScore(a){localStorage.setItem("HoldOnGame_JS13K",""+a);best=localStorage.getItem("HoldOnGame_JS13K")}starttime=new Date;animate();